### Environment Selection
env = QA

### SUT URLs
qa.base.url = https://automationexercise.com
dev.base.url = https://automationexercise-dev.com
prod.base.url = https://automationexercise-prod.com

### Browser Selection
#Browser can be chrome, firefox, edge, webkit
browser = chrome
#Headless modes can be true, false
headless = true

# Allure Report Config
screenshot.on.pass = true
screenshot.on.fail = true

# Locator Config
test-id = "data-qa"

### EXECUTION MODE
# local        = run locally with Playwright
# github       = run on GitHub Actions headless
# browserstack = run on BrowserStack cloud

execution.mode = local

### BROWSERSTACK CAPABILITIES
# These are used only when execution.mode=browserstack
# Username and accesskey passed via -D in CI

bs.project.name  = TheQEWheel - Playwright Demo
bs.build.name    = Release 1.0 - AE Tests
bs.username = 
bs.accesskey =
